spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
logging:
  level:
    com.shunshun.shirospringshun.dao: debug